language: php
php:
  - 7.4
before_script:
  - travis_retry composer self-update
  - travis_retry composer global require hirak/prestissimo
  - travis_retry composer install --no-interaction --prefer-source
script:
  - composer phpcs
  - composer phpstan
  - composer phpunit
  - composer infection
  - composer coverage
before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -e 's/^bind.*/bind 127.0.0.1/' /etc/redis/redis.conf > redis.conf
  - sudo mv redis.conf /etc/redis
  - sudo service redis-server start
  - echo PING | nc localhost 6379
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: RBUXoZJSIx26sWrc86KX7VfcYdQ33uca1++qNn/dTv3Awxyj54Ezb8NOJBuO0sz4/uVYboUXsF1CXZlbWK1DtIOdxQmuhEbpQTxPUyYmVJ4vKccCdZNO8A/5SqukQOVvpQcAhPZsPhBqDBsseeCqWvqYW6XTfnCV6WQzYJAzjKqzByY8OaSVk3mFMG9m3Fl0kbsByqr+/KLa1m7JNid7KvKnLDVjKMaUuTMRWAmcW4sIIbuFd2GuMJ7Emi8elhnUxsBB74TbFJDC66GzI0u5v57zXmaGo/9/FFtios4PN0PnC+cU75EauImwECYmQbyz27kkHc44Wg/N9NXZlUQGhN9L+fd+KJ6l3hldSIRmdGqCFXskzqn69jUpZwfXRWIbZGXarM7Q+Q5sLzzPZd0S+NkhSEDTMgeBiU+ctHdyG5rd2lLcJELDqlMqwAGH/LGO/2nPRbMypLZHTIosF1hxNC8P7GtxroDmmZ0xz4pC8YeuA9ZwS1lfHgw0cEmldsUHkIO2osP5gIE8a8nMMX9nfgFOhdcZJjWoG9cU93CE0X39yb+uR3zK4HDDOA0Bs6Y3c2FUcQH8rEjITeIdNfocTexeey/thZa+ApbkcW+EnwNcRfVuLcgpjr+H4y6Qqyn13r3twVq79tX8Z7pLwDBQZ+5OdahhpuF3oVq51hzrynY=
